version: '3.8'
services:
  backend:
    build: .
    ports:
      - "443:443"
    environment:
      - NODE_ENV=production
      - HIPAA_COMPLIANT=true
    volumes:
      - ./ssl:/app/ssl
      - ./audit_logs:/app/audit_logs
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: atis_db
      POSTGRES_USER: hipaa_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hipaa_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
